schema_version: 1

context:
  name: colorama
  version: 0.4.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/colorama-${{ version }}.tar.gz
  sha256: 08695f5cb7ed6e0531a20572697297273c47b8cae5a63ffc6d6ed5c201be6e44

build:
  number: 2
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling >=0.25.1
  run:
    - python >=3.9

tests:
  - python:
      imports:
        - colorama
      pip_check: true

about:
  homepage: https://github.com/tartley/colorama
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Cross-platform colored terminal text
  description: |
    colorama is a cross-platform colored terminal text. It makes
    ANSI escape character sequences (for producing colored terminal text
    and cursor positioning) work under MS Windows.
  documentation: http://pypi.python.org/pypi/colorama
  repository: https://github.com/tartley/colorama

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
